# Generated by Django 3.0.6 on 2020-05-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MahaPolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_data',
            name='address',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
    ]
